# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/ffmpeg-a/app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/ffmpeg-a

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/ffmpeg-a/CMakeFiles /d/ffmpeg-a//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/ffmpeg-a/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named ffmpeginterface

# Build rule for target.
ffmpeginterface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ffmpeginterface
.PHONY : ffmpeginterface

# fast build rule for target.
ffmpeginterface/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeginterface.dir/build.make CMakeFiles/ffmpeginterface.dir/build
.PHONY : ffmpeginterface/fast

src/main/cpp/ffmpeginterface.o: src/main/cpp/ffmpeginterface.cpp.o
.PHONY : src/main/cpp/ffmpeginterface.o

# target to build an object file
src/main/cpp/ffmpeginterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeginterface.dir/build.make CMakeFiles/ffmpeginterface.dir/src/main/cpp/ffmpeginterface.cpp.o
.PHONY : src/main/cpp/ffmpeginterface.cpp.o

src/main/cpp/ffmpeginterface.i: src/main/cpp/ffmpeginterface.cpp.i
.PHONY : src/main/cpp/ffmpeginterface.i

# target to preprocess a source file
src/main/cpp/ffmpeginterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeginterface.dir/build.make CMakeFiles/ffmpeginterface.dir/src/main/cpp/ffmpeginterface.cpp.i
.PHONY : src/main/cpp/ffmpeginterface.cpp.i

src/main/cpp/ffmpeginterface.s: src/main/cpp/ffmpeginterface.cpp.s
.PHONY : src/main/cpp/ffmpeginterface.s

# target to generate assembly for a file
src/main/cpp/ffmpeginterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ffmpeginterface.dir/build.make CMakeFiles/ffmpeginterface.dir/src/main/cpp/ffmpeginterface.cpp.s
.PHONY : src/main/cpp/ffmpeginterface.cpp.s

src/main/cpp/hello.o: src/main/cpp/hello.cpp.o
.PHONY : src/main/cpp/hello.o

# target to build an object file
src/main/cpp/hello.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/main/cpp/hello.cpp.o
.PHONY : src/main/cpp/hello.cpp.o

src/main/cpp/hello.i: src/main/cpp/hello.cpp.i
.PHONY : src/main/cpp/hello.i

# target to preprocess a source file
src/main/cpp/hello.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/main/cpp/hello.cpp.i
.PHONY : src/main/cpp/hello.cpp.i

src/main/cpp/hello.s: src/main/cpp/hello.cpp.s
.PHONY : src/main/cpp/hello.s

# target to generate assembly for a file
src/main/cpp/hello.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/main/cpp/hello.cpp.s
.PHONY : src/main/cpp/hello.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ffmpeginterface"
	@echo "... hello"
	@echo "... src/main/cpp/ffmpeginterface.o"
	@echo "... src/main/cpp/ffmpeginterface.i"
	@echo "... src/main/cpp/ffmpeginterface.s"
	@echo "... src/main/cpp/hello.o"
	@echo "... src/main/cpp/hello.i"
	@echo "... src/main/cpp/hello.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

